app.controller('dgroomCtrl', ['$scope', function ($scope) {
    console.log("dgroomCtrl");
    $scope.gridsterOpts = {
        minRows: 2, // the minimum height of the grid, in rows
        maxRows: 100,
        columns: 6, // the width of the grid, in columns
        colWidth: 'auto', // can be an integer or 'auto'.  'auto' uses the pixel width of the element divided by 'columns'
        rowHeight: 'match', // can be an integer or 'match'.  Match uses the colWidth, giving you square widgets.
        margins: [10, 10], // the pixel distance between each widget
        defaultSizeX: 2, // the default width of a gridster item, if not specifed
        defaultSizeY: 1, // the default height of a gridster item, if not specified
        mobileBreakPoint: 600, // if the screen is not wider that this, remove the grid layout and stack the items
        resizable: {
            enabled: true,
            start: function (event, uiWidget, $element) {
            }, // optional callback fired when resize is started,
            resize: function (event, uiWidget, $element) {
            }, // optional callback fired when item is resized,
            stop: function (event, uiWidget, $element) {
            } // optional callback fired when item is finished resizing
        },
        draggable: {
            enabled: true, // whether dragging items is supported
            handle: '.ddd', // optional selector for resize handle
            start: function (event, uiWidget, $element) {
            }, // optional callback fired when drag is started,
            drag: function (event, uiWidget, $element) {
            }, // optional callback fired when item is moved,
            stop: function (event, uiWidget, $element) {
            } // optional callback fired when item is finished dragging
        }
    };
    $scope.panel =  [
        {
            "label": "LT Panel: LT Panel Incomer-1",
            "data": [
        
                {
                    "TagId": 437,
                    "Parameter": "VoltagePhase-RY",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 438,
                    "Parameter": "VoltagePhase-R",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 439,
                    "Parameter": "VoltagePhase-YB",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 440,
                    "Parameter": "VoltagePhase-Y",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 441,
                    "Parameter": "VoltagePhase-BR",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 442,
                    "Parameter": "VoltagePhase-B",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 443,
                    "Parameter": "CurrentPhase-R",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 444,
                    "Parameter": "CurrentPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 445,
                    "Parameter": "CurrentPhase-B",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 446,
                    "Parameter": "ActivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 447,
                    "Parameter": "ReactivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 448,
                    "Parameter": "ApparentPowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 449,
                    "Parameter": "ActivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 450,
                    "Parameter": "ReactivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 451,
                    "Parameter": "ApparentPowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 452,
                    "Parameter": "ActivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 453,
                    "Parameter": "ReactivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 454,
                    "Parameter": "ApparentPowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 455,
                    "Parameter": "PowerFactorPhase-R",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 456,
                    "Parameter": "PowerFactorPhase-Y",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 457,
                    "Parameter": "PowerFactorPhase-B",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 458,
                    "Parameter": "LineFrequencyHz",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 459,
                    "Parameter": "EnergyKWh",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 460,
                    "Parameter": "vTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 461,
                    "Parameter": "iTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 462,
                    "Parameter": "vTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 463,
                    "Parameter": "iTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 464,
                    "Parameter": "vTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 465,
                    "Parameter": "iTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }
            ]
        },
        {
            "label": "LT Panel: LT Panel Incomer-1",
            "data": [
        
                {
                    "TagId": 437,
                    "Parameter": "VoltagePhase-RY",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 438,
                    "Parameter": "VoltagePhase-R",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 439,
                    "Parameter": "VoltagePhase-YB",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 440,
                    "Parameter": "VoltagePhase-Y",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 441,
                    "Parameter": "VoltagePhase-BR",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 442,
                    "Parameter": "VoltagePhase-B",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 443,
                    "Parameter": "CurrentPhase-R",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 444,
                    "Parameter": "CurrentPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 445,
                    "Parameter": "CurrentPhase-B",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 446,
                    "Parameter": "ActivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 447,
                    "Parameter": "ReactivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 448,
                    "Parameter": "ApparentPowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 449,
                    "Parameter": "ActivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 450,
                    "Parameter": "ReactivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 451,
                    "Parameter": "ApparentPowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 452,
                    "Parameter": "ActivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 453,
                    "Parameter": "ReactivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 454,
                    "Parameter": "ApparentPowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 455,
                    "Parameter": "PowerFactorPhase-R",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 456,
                    "Parameter": "PowerFactorPhase-Y",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 457,
                    "Parameter": "PowerFactorPhase-B",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 458,
                    "Parameter": "LineFrequencyHz",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 459,
                    "Parameter": "EnergyKWh",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 460,
                    "Parameter": "vTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 461,
                    "Parameter": "iTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 462,
                    "Parameter": "vTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 463,
                    "Parameter": "iTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 464,
                    "Parameter": "vTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 465,
                    "Parameter": "iTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }
            ]
        },
        {
            "label": "LT Panel: LT Panel Incomer-1",
            "data": [
        
                {
                    "TagId": 437,
                    "Parameter": "VoltagePhase-RY",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 438,
                    "Parameter": "VoltagePhase-R",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 439,
                    "Parameter": "VoltagePhase-YB",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 440,
                    "Parameter": "VoltagePhase-Y",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 441,
                    "Parameter": "VoltagePhase-BR",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 442,
                    "Parameter": "VoltagePhase-B",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 443,
                    "Parameter": "CurrentPhase-R",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 444,
                    "Parameter": "CurrentPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 445,
                    "Parameter": "CurrentPhase-B",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 446,
                    "Parameter": "ActivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 447,
                    "Parameter": "ReactivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 448,
                    "Parameter": "ApparentPowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 449,
                    "Parameter": "ActivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 450,
                    "Parameter": "ReactivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 451,
                    "Parameter": "ApparentPowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 452,
                    "Parameter": "ActivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 453,
                    "Parameter": "ReactivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 454,
                    "Parameter": "ApparentPowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 455,
                    "Parameter": "PowerFactorPhase-R",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 456,
                    "Parameter": "PowerFactorPhase-Y",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 457,
                    "Parameter": "PowerFactorPhase-B",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 458,
                    "Parameter": "LineFrequencyHz",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 459,
                    "Parameter": "EnergyKWh",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 460,
                    "Parameter": "vTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 461,
                    "Parameter": "iTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 462,
                    "Parameter": "vTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 463,
                    "Parameter": "iTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 464,
                    "Parameter": "vTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 465,
                    "Parameter": "iTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }
            ]
        },{
            "label": "LT Panel: LT Panel Incomer-1",
            "data": [
        
                {
                    "TagId": 437,
                    "Parameter": "VoltagePhase-RY",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 438,
                    "Parameter": "VoltagePhase-R",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 439,
                    "Parameter": "VoltagePhase-YB",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 440,
                    "Parameter": "VoltagePhase-Y",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 441,
                    "Parameter": "VoltagePhase-BR",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 442,
                    "Parameter": "VoltagePhase-B",
                    "Value": 1,
                    "EnggUnit": "Volt"
                }, {
                    "TagId": 443,
                    "Parameter": "CurrentPhase-R",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 444,
                    "Parameter": "CurrentPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 445,
                    "Parameter": "CurrentPhase-B",
                    "Value": 1,
                    "EnggUnit": "Amp"
                }, {
                    "TagId": 446,
                    "Parameter": "ActivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 447,
                    "Parameter": "ReactivePowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 448,
                    "Parameter": "ApparentPowerPhase-R",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 449,
                    "Parameter": "ActivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 450,
                    "Parameter": "ReactivePowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 451,
                    "Parameter": "ApparentPowerPhase-Y",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 452,
                    "Parameter": "ActivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Watt"
                }, {
                    "TagId": 453,
                    "Parameter": "ReactivePowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 454,
                    "Parameter": "ApparentPowerPhase-B",
                    "Value": 1,
                    "EnggUnit": "Var"
                }, {
                    "TagId": 455,
                    "Parameter": "PowerFactorPhase-R",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 456,
                    "Parameter": "PowerFactorPhase-Y",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 457,
                    "Parameter": "PowerFactorPhase-B",
                    "Value": 1,
                    "EnggUnit": "PF"
                }, {
                    "TagId": 458,
                    "Parameter": "LineFrequencyHz",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 459,
                    "Parameter": "EnergyKWh",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 460,
                    "Parameter": "vTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 461,
                    "Parameter": "iTHDPhase-R",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 462,
                    "Parameter": "vTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 463,
                    "Parameter": "iTHDPhase-Y",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 464,
                    "Parameter": "vTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }, {
                    "TagId": 465,
                    "Parameter": "iTHDPhase-B",
                    "Value": 1,
                    "EnggUnit": ""
                }
            ]
        }
      
    ]
}])